version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8001:8000'        # Exponer el puerto 8000 del backend en el 8001 del host
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3003:3000'        # React DevServer mapeado en el puerto 3003 del host
    depends_on:
      - backend
    environment:
      # Fuerza a React a usar polling para hot‐reload en Docker 
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
