version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge